# drums
xg_list_1 =   ("13 Surdo Mute",
               "14 Surdo Open",
               "15 Hi Q",
               "16 Whip Slap",
               "17 Scratch H",
               "18 Scratch L",
               "19 Finger Snap",
               "20 Click Noise",
               "21 Metronome Click",
               "22 Metronome Bell]",
               "23 Seq Click L",
               "24 Seq Click H",
               "25 Brush Tap",
               "26 Brush Swirl",
               "27 Brush Slap",
               "28 Brush Tap Swirl",
               "29 Snare Roll",
               "30 Castanet",
               "31 Snare Soft",
               "32 Sticks",
               "33 Kick Soft",
               "34 Open Rim Shot")

gs_list_1 =  ("22 MC-500 Beep 1",
              "23 MC-500 Beep 2",
              "24 Concert SD",
              "25 Snare Roll",
              "26 Finger Snap 2",
              "27 High Q",
              "28 Slap",
              "29 Scratch Push",
              "30 Scratch Pull",
              "31 Sticks",
              "32 Square Click",
              "33 Metronome Click",
              "34 Metronome Bell")

gm_list_drums =  ("35 Kick Drum 2",
                  "36 Kick Drum 1",
                  "37 Side Stick",
                  "38 Snare Drum 1",
                  "40 Snare Drum 2",
                  "41 Low Tom 1",
                  "43 Low Tom 2",
                  "45 Mid Tom 1",
                  "47 Mid Tom 2",
                  "48 High Tom 1",
                  "50 High Tom 2")

gm_list_cym =  ("42 Hi-hat Closed",
                "44 Hi-hat Pedal",
                "46 Hi-hat Open",
                "49 Cymbal Crash 1",
                "51 Cymbal Ride 1",
                "52 Cymbal Chinese",
                "53 Cymbal Ride Bell",
                "55 Cymbal Splash",
                "57 Cymbal Crash 2",
                "59 Cymbal Ride 2")

gm_list_perc = ("39 Hand Clap",
                "54 Tambourine",
                "56 Cowbell",
                "58 Vibra-slap",
                "60 High Bongo",
                "61 Low Bongo",
                "62 Mute High Conga",
                "63 Open High Conga",
                "64 Low Conga",
                "65 High Timbale",
                "66 Low Timbale",
                "67 High Agogo",
                "68 Low Agogo",
                "69 Cabasa",
                "70 Maracas",
                "71 Short Hi Whistle",
                "72 Long Low Whistle",
                "73 Short Guiro",
                "74 Long Guiro",
                "75 Claves",
                "76 High Wood Block",
                "77 Low Wood Block",
                "78 Mute Cuica",
                "79 Open Cuica",
                "80 Mute Triangle",
                "81 Open Triangle",
                "82 Shaker",
                "83 Jingle Bell",
                "84 Bell Tree",
                "85 Castanets",
                "86 Mute Surdo",
                "87 Open Surdo",
                "88 Applause 2")